import { CONSTRUCT_LABELS, CONSTRUCT_ORDER } from "./api";

// Fixed Meridian round titles (not carried in the debrief payload).
const ROUND_TITLES = {
  1: "Trust the Feed",
  2: "Diagnose the Gap",
  3: "Combine & Automate",
  4: "Tell the Visual Story",
  5: "Board Synthesis",
};

// Student-facing coaching per graded field — names the dimension to revisit WITHOUT
// revealing the canonical answer (the facilitator reveals exact answers in the debrief).
const COACHING = {
  "Bluetooth revenue": "Re-derive the revenue figure from the cleaned feed.",
  "Data-issue tags": "One data-quality issue type went unflagged — re-scan the feed.",
  "Root cause": "Revisit which driver best explains the regional gap.",
  "Attainment gap": "Recompute the attainment gap.",
  "Combined row count": "Recount the rows in the combined dataset.",
  "Combined revenue": "Re-check the reconciled revenue total.",
  "Most-ordered product": "Re-check which product had the most orders.",
  "Product order count": "Recount that product's orders.",
  "Peak month": "Re-check which month had the highest volume.",
  "Peak-month order count": "Recount the peak month's orders.",
};

const band = (v) => (v == null ? "na" : v >= 75 ? "high" : v >= 40 ? "mid" : "low");

/**
 * Per-team takeaway report, generated by the facilitator from the debrief data and
 * printed to PDF for the students. Student-facing: it shows scores, the construct
 * profile, round outcomes and what to revisit — but never the canonical answers.
 */
export default function Sim2TeamReport({ team, leaderboard, simulationName, onClose }) {
  const scores = team.scores || {};
  const subs = {};
  (team.submissions || []).forEach((s) => (subs[s.roundNumber] = s));

  const standing = (construct) => {
    const rows = leaderboard?.constructs?.[construct] || [];
    const row = rows.find((r) => r.teamName === team.teamName);
    return row ? { ...row, outOf: rows.length } : null;
  };

  // Overall: mean of the graded-round outcomes, and the mean construct percentile.
  const graded = (team.submissions || []).filter((s) => s.outcomePct != null);
  const meanOutcome = graded.length
    ? Math.round(graded.reduce((a, s) => a + s.outcomePct, 0) / graded.length)
    : null;
  const pctiles = CONSTRUCT_ORDER.map((c) => standing(c)?.percentile).filter((p) => p != null);
  const meanPctile = pctiles.length
    ? Math.round(pctiles.reduce((a, p) => a + p, 0) / pctiles.length)
    : null;

  // Strength / development from the highest and lowest scored constructs.
  const scored = CONSTRUCT_ORDER.filter((c) => scores[c] != null).sort((a, b) => scores[b] - scores[a]);
  const strength = scored[0];
  const development = scored[scored.length - 1];
  const hcw = team.highConfidenceWrongRounds || [];

  const when = (ts) =>
    ts ? new Date(ts).toLocaleDateString([], { day: "numeric", month: "short", year: "numeric" }) : "—";

  return (
    <div className="rpt-scrim" onClick={onClose}>
      <div className="rpt-toolbar" onClick={(e) => e.stopPropagation()}>
        <span>Report · {team.teamName}</span>
        <div>
          <button onClick={() => window.print()}>Print / Save as PDF</button>
          <button className="f-ghost" onClick={onClose}>Close</button>
        </div>
      </div>

      <div className="rpt-sheet" onClick={(e) => e.stopPropagation()}>
        <div className="rpt-mast">
          <div className="rpt-brand">CaseRun<small>Leadership Analytics Report</small></div>
        </div>

        <div className="rpt-pad">
          <h1 className="rpt-title">{team.teamName}</h1>
          <div className="rpt-sub">{simulationName || "Meridian Retail — Quarterly Business Review"}</div>
          <div className="rpt-meta">
            <div><b>Format</b>5 rounds · 90 minutes</div>
            <div><b>Completed</b>{when(team.finishedAt)}</div>
            {meanOutcome != null && <div><b>Mean round outcome</b>{meanOutcome}%</div>}
            {meanPctile != null && <div><b>Cohort percentile</b>{meanPctile}th</div>}
          </div>
        </div>

        <div className="rpt-pad rpt-block">
          <div className="rpt-label">Leadership construct profile</div>
          {CONSTRUCT_ORDER.map((c) => {
            const v = scores[c];
            const st = standing(c);
            return (
              <div className="rpt-bar-row" key={c}>
                <div className="rpt-bar-name">
                  {CONSTRUCT_LABELS[c]}
                  {st && <span> · {st.rank} of {st.outOf} · {st.percentile}th pct</span>}
                </div>
                <div className="rpt-track">
                  <div className={`rpt-fill rpt-${band(v)}`} style={{ width: `${v == null ? 0 : v}%` }} />
                </div>
                <div className="rpt-bar-val">{v == null ? "—" : v}</div>
              </div>
            );
          })}
        </div>

        <div className="rpt-pad rpt-block">
          <div className="rpt-label">How the quarter unfolded</div>
          <table className="rpt-table">
            <thead>
              <tr><th>Round</th><th>Focus</th><th>What to revisit</th><th className="r">Outcome</th></tr>
            </thead>
            <tbody>
              {[1, 2, 3, 4, 5].map((n) => {
                const s = subs[n];
                const missed = (s?.feedback || []).filter((f) => !f.ok);
                const revisit =
                  n === 5
                    ? "Free-text board reflection"
                    : !s
                    ? "—"
                    : missed.length === 0
                    ? "Fully correct"
                    : missed.map((f) => COACHING[f.label] || `Revisit: ${f.label}`).join(" ");
                return (
                  <tr key={n}>
                    <td className="rpt-rn">R{n}</td>
                    <td>{ROUND_TITLES[n]}</td>
                    <td className={missed.length === 0 && s ? "rpt-ok" : ""}>{revisit}</td>
                    <td className="r">{s?.outcomePct == null ? "—" : `${s.outcomePct}%`}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>

        <div className="rpt-pad rpt-block">
          <div className="rpt-label">What the data says</div>
          <p className="rpt-narr">
            {team.dataTrustFirstDropRound ? (
              <>Your Data Trust first dropped at <b>Round {team.dataTrustFirstDropRound}</b> ({team.dataTrustPattern}) — in this
              simulation an early miss on the numbers quietly follows the team toward the Board.</>
            ) : (
              <>Your Data Trust held across all five rounds — the numbers you put in front of the Board stayed defensible throughout.</>
            )}
          </p>
          <p className="rpt-narr">
            {hcw.length > 0 ? (
              <>In Round{hcw.length > 1 ? "s" : ""} {hcw.join(", ")} you answered with high confidence but were off — worth
              recalibrating how confidence tracks the evidence.</>
            ) : (
              <>Your confidence tracked your correctness well — no overconfident misses.</>
            )}
          </p>
        </div>

        <div className="rpt-pad rpt-block rpt-cols">
          <div className="rpt-panel">
            <h4>Strength</h4>
            <p>{strength ? <>Your strongest construct was <b>{CONSTRUCT_LABELS[strength]}</b> ({scores[strength]}).</> : "—"}</p>
          </div>
          <div className="rpt-panel">
            <h4>Development area</h4>
            <p>{development ? <>Focus next on <b>{CONSTRUCT_LABELS[development]}</b> ({scores[development]}).</> : "—"}</p>
          </div>
        </div>

        <div className="rpt-foot">
          CaseRun scores five leadership constructs from every decision a team makes, benchmarked against the cohort.
          This report shows <b>what to revisit</b>; your facilitator walks through the correct answers in the live debrief. © CaseRun.
        </div>
      </div>
    </div>
  );
}
